language: java
install: skip
os: linux
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure:
  app: testing-travis
  on:
    repo: testing-travis
  scipt:
    - chmod +x ./gradlew
    - ./gradlew clean build
