language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: Uci6yJx4W5w2GpFd7XnexFgc0uWmJ+XfxoTydZThmpx7Ig7O5enVaOOLyRT75yq3WxcTcuT+wNC/mT1V8F5yeYkhFvuF2dcnFEygz59OOuevMYS6mmFIHZ3o2DKmDfcX8UdsffLova1h9oIZbR2rSRfHREAG/FLn/Ym8fnJfiEe7QHOixZehYNs2cFVb5mrPHnmw9+3DrWxcIvmORpKH8sMsaWDu2gnLoXoXyykx3Qscw7mwyxr++Z8GW0xjBRY7n7MOMg4iBBwMaN70yK9ZmsYLFgWtGt32WnR8vSaY73l/qMMe6QBidgG2GYiskLV/uDf+DhHngR1eQf8KS/eAEe/vHXLyZ4WDJgfIUmQhQYurFA3W+Eq/tTMV3oR8EkDGXqyVbUVi5J473mUsRsahUEA0XmM/UizkX0Ze/JyUM8M60J3kTjkRfBEt6RKBOc2yN0P+KeAD174rp7S/qqgLVmtDTQtu/72xv99T8CqdTKnLg0P4jeWuZS9E4CzLsqOByi2u7Ytjir+ycAwl9L87876bacU+g+xdOKQAZ2QMRkO4hXnFpm/Yb6JV2jT34dFtBBOXcBXGKIVCt6JWzqmyPmKKmxdifhMh6WfH5j1zfmTK67D+Zcf3Cke6SDaxwY7icewYlr+2jhJ8mUyZ58whSggAyn85sJWrU4dfs/UHVPw=
  app: stormy-garden-18192
  on:
    repo: PiXHULA/testing-travis
addons:
  sonarcloud:
    organization: "pixhula"
    token:
      secure: "**************************"
script:
  - "chmod +x ./gradlew"
  - "./gradlew clean build"
  - "./gradlew sonarqube"
env:
  global:
    secure: ssRTLO2UtEOOuogvx8fiZYD5YcawdLGGh6mKOgqjAnfeM1g90awrkw9HmrzI4/kfMyvTmAqzq/qdN3kdv9eGRLttBOV69EbHRaWBm9TtK92GPfXiuNaD4QOXW62QT0whloh/IrVOcEy5Mu9KgtSzCX//3nsl2k5TFNWe84t3U7BnN7QNIpApbPM4bFKbAhWPNee5OAJK8U+LZYJAU1zDn2OAy2MFWZW/8yDu/+SYl48yrm39cOZZTulLF9wo0picyHNRLx+LOiBg0H52LVw+ZD11scOq/Is3mSTjeMzJK58hu5sQqIe5ftcOi7BJbFrUwi00Lo1a9vYzvR9oeh5SME8lyclhuroty/i4CqgYqRReEfbyfdvs6Ecfo1pECQ3y+4duu73rVXLt3zVDlLCdrEx8hAFFOVCACodgwBnACNcQP0xOgPtsv0ZUqAuMFSOf103pn7u0cCWVD0Bcny2/fcS4ozQBUFlgUnA72BGa61NCLP7XRiOfnXz9deMg8u3uTv4C3b6v+fh2L6CqVaXe3t1fI0DjnZ0WV9v/uboO0QppNTZrJvv9Xc6UWXlavZ1JXXE9zchaPGMnpPI8SBas4/iZnuwWgb4nDk7XTiQ/smi+TOo22jSrZKVHtbtVTIlM/u2tg4hYDaZidImD1zLVWXywSKmKJ0SqZ976dgLc+1o=
