language: java
install: skip
os: linux
jdk: openjdk14
deploy:
  provider: heroku
  api_key:
    secure: Uci6yJx4W5w2GpFd7XnexFgc0uWmJ+XfxoTydZThmpx7Ig7O5enVaOOLyRT75yq3WxcTcuT+wNC/mT1V8F5yeYkhFvuF2dcnFEygz59OOuevMYS6mmFIHZ3o2DKmDfcX8UdsffLova1h9oIZbR2rSRfHREAG/FLn/Ym8fnJfiEe7QHOixZehYNs2cFVb5mrPHnmw9+3DrWxcIvmORpKH8sMsaWDu2gnLoXoXyykx3Qscw7mwyxr++Z8GW0xjBRY7n7MOMg4iBBwMaN70yK9ZmsYLFgWtGt32WnR8vSaY73l/qMMe6QBidgG2GYiskLV/uDf+DhHngR1eQf8KS/eAEe/vHXLyZ4WDJgfIUmQhQYurFA3W+Eq/tTMV3oR8EkDGXqyVbUVi5J473mUsRsahUEA0XmM/UizkX0Ze/JyUM8M60J3kTjkRfBEt6RKBOc2yN0P+KeAD174rp7S/qqgLVmtDTQtu/72xv99T8CqdTKnLg0P4jeWuZS9E4CzLsqOByi2u7Ytjir+ycAwl9L87876bacU+g+xdOKQAZ2QMRkO4hXnFpm/Yb6JV2jT34dFtBBOXcBXGKIVCt6JWzqmyPmKKmxdifhMh6WfH5j1zfmTK67D+Zcf3Cke6SDaxwY7icewYlr+2jhJ8mUyZ58whSggAyn85sJWrU4dfs/UHVPw=
  app: stormy-garden-18192
  on:
    repo: PiXHULA/testing-travis
addons:
  sonarcloud:
    organization: "pixhula"
    token:
      secure: "BTwf1nc03rIO/F4KJ6KOA4gtDTFHQlYwg1SBidMqT8WQvSaIN9nG0ffqRFazVm7SUnrh3sKhY4zmrWF17nRftwzsgMEs3Kx/+dODOnOPhUifVJpx4B3V2+dqtycTjUD+KR3Ja8yp3vJaWn99prf+SCWP9LrWm55TR5vsS+oqSkFfizjUMhsnb0aFD/h8J11mCBZGt+c+ZVMjoREjAHEpevePEjakgUbaeU3ND99LS6wrpdSJAdzenaU5YCY9PaVz0ZHX2HVJDv/ViMZBDX4+eEmmFuetZ1KIRxVJ0WoBraV+BU4yEQHJkgEF6tkOGhMW+yevPbpVeqgMeLgGP+kE6LajyHN9xQ6FRu3DZ6+dbPOx8Rqha5SdIaPKjCwIovHK5LtJQsbsRiEBVrTSZMVPBa0oX0y+vNieh2IoH3bem0IkQefoz7GZcHtrJqIT0y7gsYVmn4Z7sHGnICWNtXNgjQG5P1kEeLN3ex6AY5cZ64OLR/Y95fT7F6/fZwzxr+jrYHw4ozJrW0owwTj6/JZ5tsYAlqIAJQhtmCAEiV5zjZNKEd6EVuSNB2Qm8jmgaJXCtuOieMOJQGJsOAt+EwdVlCcvdjUSmL2fsTC4y6hJ06CjCOxNQAsONv/a3yyNhOkDz7EV6IHLyfhjDq7J7OWczfnX441dSG7JT/jNicFXG6I="
script:
  - "chmod +x ./gradlew"
  - "./gradlew clean build"
  - "./gradlew sonarqube"
