language: java
install: skip
os: linux
jdk: openjdk11
deploy:
  provider: heroku
  api_key:
    secure: 733d9986-78b3-4f96-a82d-636409400e13
  app: stormy-garden-18192
  on:
    repo: PiXHULA/testing-travis
  scipt:
    - travis encrypt 733d9986-78b3-4f96-a82d-636409400e13 --add deploy.api_key --org
    - chmod +x ./gradlew
    - ./gradlew clean build
