package com.example.demo.domain;

import lombok.*;

import javax.persistence.*;

@Entity
@Table (name = "applications") //Might be autogenerated with the schema?
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
public final class Application {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long Id;
    private String logo;
    private String link;

}
