package com.example.demo.domain;

import lombok.*;
import org.springframework.format.annotation.DateTimeFormat;


import javax.persistence.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "packages") //Might be autogenerated with the schema?
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
public final class Package {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long Id;
//    @DateTimeFormat(pattern = "E, dd-MM-yyyy")
//    private LocalDateTime date;
//    private String curator;
//    private String curatorPicture;
//    //@NotBlank(message = "Title should not be blank")
//    private String title;
//    //@NotBlank(message = "Tag should not be blank")
//    private String tag;
//    //@NotBlank(message = "City should not be blank")
//    private String city;
//    //@NotBlank(message = "Description should not be blank")
//    private String description;

    @OneToMany
    private List<Application> applications; //Set? For unique apps
}
